config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "questions#index"

  resources :questions do
    resources :answers
  end
  
  resources :users

  namespace :api do
    namespace :v1 do
      resources :questions, only: [:index, :show]
    end
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  validates :answer, presence: true

  belongs_to :user
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  validates :title, length: {maximum: 140}, presence: true

  belongs_to :user
  has_many :answers, :dependent => :delete_all
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :questions
  has_many :answers
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def index
    @question = Question.find(params[:question_id])
    @answer = @question.answer
  end

  def new
    @question = Question.find(params[:question_id])
    @answer = Answer.new
  end

  def create
    @answer = Answer.new(answer_params)
    @question = Question.find(params[:question_id])
    @answer.question = @question
    @answer.user = current_user
    if @answer.save
      redirect_to @question
    else
      flash[:notice] = @answer.errors.full_messages.to_sentence
      render :new
    end
  end

  private

  def answer_params
    params.require(:answer).permit(:answer)
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < ApplicationController
  def index
    questions = Question.all.order(created_at: :desc)
    answers = Answer.all.order(created_at: :desc)
    render json: {questions: questions, answers: answers}
  end

  def show
    question = Question.find(params[:id])
    answers = question.answers
    users = User.all
    render json: {question: question, answers: answers, users: users}
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all.order(created_at: :desc)
  end

  def show
    @question = Question.find(params[:id])
    @question.description ||= "No description provided for this question."
    @answers = @question.answers
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    @question.user = current_user
    if @question.save
      redirect_to @question
    else
      flash[:notice] = @question.errors.full_messages.to_sentence
      render :new
    end
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])

    if @question.update(question_params)
      redirect_to @question
    else
      flash[:notice] = @question.errors.full_messages.to_sentence
      render :edit
    end
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy
    redirect_to questions_path
  end

  private

  def question_params
    params.require(:question).permit(:title, :description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/answers/_form.html.erb
<%= form_for [@question, @answer] do |f| %>
  <div>
    <%= f.label :answer %>
    <%= f.text_field :answer %>
  </div>
  <div>
    <%= f.submit "Submit Answer"%>
  </div>
<% end %>

app/views/answers/new.html.erb
<div class="content-box">
  <div>
    <%= "Question: #{@question.title}" %>
  </div>
  <% unless @question.description.nil? %>
    <div>
      <%= "Description: #{@question.description}" %>
    </div>
  <% end %>

  <%= render 'form' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Homework Helper</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <nav id="nav-bar" data-topbar role="navigation">
      <div class="title-area" >
        <h1 class="site-name"><a href="/questions">Homework Helper</a></h1>
        <div class="search-bar">
          A Search bar will go here
        </div>
        <div class="users-button">
          <%= button_to "Users", users_path, method: "get" %>
        </div>
        <% if user_signed_in? %>
          <div class="log-out-button">
            <%= button_to 'Sign Out', destroy_user_session_path, :method => :delete %>
          </div>
        <% else %>
          <div class="login-options">
            <div class="sign-up-button">
              <%= button_to "Sign Up", new_user_registration_path, method: "get" %>
            </div>
            <div class="login-button">
              <%= button_to "Log In", new_user_session_path, method: "get" %>
            </div>
          </div>
        <% end %>
      </div>
    </nav>
    <div class="nav-bar-spacer">

    </div>
    <% if flash[:notice] %>
      <div id="flash-notice">
        <%= flash.notice %>
      </div>
      <script type="text/javascript">
        $(document).ready(function(){
          setTimeout(function(){
            $('#flash-notice').fadeOut();
          }, 3000);
        })
      </script>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <div>
    <%= f.label :title, "Question" %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>
  <div>
    <%= f.submit 'Submit Question' %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<div class='content-box'>
  <h1>Edit Question</h1>
  <h3> <%= "Question: " + @question.title %> </h3>
  <% unless @question.description.empty? %>
    <h3> <%= "Question description: " + @question.description %> </h3>
  <% end %>

  <%= render 'form' %>

  <%= link_to "Back", question_path(@question) %>
</div>

app/views/questions/index.html.erb
<div class="page">
  <div class="main-bar">

    <div id="questions-index-header">
      <div id="index-title">Questions</div>
      <% if user_signed_in? %>
        <div id="ask-a-question-div">
          <%= button_to 'Ask a question', new_question_path, method: 'get' %>
        </div>
      <% end %>
    </div>

    <div id="question-list">
    </div>
  </div>
  <div class="advertisement">
      <p>once this blows up, i'll charge chegg like $0.005 per ad and I'll be rich</p>
  </div>
</div>

app/views/questions/new.html.erb
<div class='content-box'>
  <h1>Ask a question</h1>

  <%= render 'form' %>

  <%= link_to "Back", questions_path %>
</div>

app/views/questions/show.html.erb
<div class="page" id=<%= @question.id.to_s %>>
  <div class="main-bar">
    <div id="answers-list"></div>

    <div class="question-links">
      <div class="answer-question">
        <%= form_for [@question, Answer.new] do |f| %>
          <div>
            <%= f.label :answer, "Your Answer" %>
          </div>
          <div>
            <%= f.text_area :answer, cols: 100, rows: 10 %>
          </div>
          <div>
            <%= f.submit "Submit Answer"%>
          </div>
        <% end %>
      </div>
      <div id="edit-question">
        <%= button_to 'Edit question', edit_question_path , method: 'get'%>
      </div>
      <div id="delete-question">
        <%= button_to 'Delete question', @question, method: :delete, data: { confirm: "Are you sure you want to delete this question? This question and all of its answers will be destroyed and will be unable to be recovered. Confirm?" } %>
      </div>
      <div id="back-to-questions">
        <%= button_to 'Back to questions', questions_path, method: 'get' %>
      </div>
    </div>
  </div>
  <div class="advertisement">
      <p>once this blows up, i'll charge chegg like $0.005 per ad and I'll be rich</p>
  </div>
</div>

app/views/users/index.html.erb
<div class="users-page">
  <div class="users-list">
    <% @users.each_slice(3) do |slice| %>
      <div class="row">
        <% slice.each do |user| %>
          <div class="user-div">
            <%= link_to user.username, user %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="page">
  <div class="user-card">
    <div class="user-photo">
      <p>A photo will go here. Display your uniqueness through a picture!</p>
    </div>
    <div class="user-info">
      <div class="username">
        <h1> <%= @user.username %> </h1>
      </div>
      <div class="user-desctiption">
        <p>user desctiption will go here</p>
      </div>
    </div>
    <div class="user-sidebar">
      <div class="user-stats">
        <div class="user-questions">
          <p> <%= @user.questions.size %> </p>
          <p>questions</p>
        </div>
        <div class="user-answers">
          <p> <%= @user.answers.size %> </p>
          <p>answers</p>
        </div>
      </div>
      <div class="user-links">
        user links/other profile stats will go here
      </div>
    </div>
  </div>
</div>